name: metamon
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - atk-1.0=2.36.0=ha1a6a79_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.16.0=hb05425b_5
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.11=py310h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gdk-pixbuf=2.42.10=h5eee18b_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.69.1=h4ff587b_1
  - gobject-introspection=1.72.0=py310hbb6d50b_0
  - graphite2=1.3.14=h295c915_1
  - gtk2=2.24.33=h73c1081_2
  - gts=0.7.6=hb67d8dd_3
  - harfbuzz=4.3.0=hf52aaf7_2
  - icu=73.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.20.1=h568e23c_1
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libboost=1.82.0=h109eef0_2
  - libcurl=8.2.1=h91b91d3_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgd=2.3.3=h6a678d5_3
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libnghttp2=1.52.0=ha637b67_1
  - libpng=1.6.39=h5eee18b_0
  - librsvg=2.54.4=h36cc946_3
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libtool=2.4.7=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.10.4=hfdd30dd_2
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=1.1.1w=h7f8727e_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.50.7=h05da053_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre=8.45=h295c915_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - pixman=0.46.4=h7934f7d_0
  - poppler=22.12.0=h9614445_3
  - poppler-data=0.4.11=h06a4308_1
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.0=h12debd9_5
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - pyzmq=26.2.0=py310h6a678d5_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py310h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - accelerate==1.10.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.0.0
      - dill==0.3.8
      - einops==0.8.1
      - farama-notifications==0.0.4
      - filelock==3.19.1
      - fonttools==4.59.2
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - gin-config==0.5.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - graphviz==0.21
      - grpclib==0.4.8
      - gym==0.26.2
      - gym-notices==0.1.0
      - gymnasium==0.29.1
      - h2==4.3.0
      - hf-xet==1.1.7
      - hpack==4.1.0
      - huggingface-hub==0.34.4
      - hyperframe==6.1.0
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lz4==4.4.4
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - mdurl==0.1.2
      - modal==1.1.4
      - mpmath==1.3.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - networkx==3.4.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - orjson==3.11.2
      - pandas==2.3.1
      - pillow==11.3.0
      - platformdirs==4.3.8
      - propcache==0.3.2
      - protobuf==6.32.0
      - psutil==7.0.0
      - pyarrow==21.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.4
      - rich==14.1.0
      - safetensors==0.6.2
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentry-sdk==2.35.0
      - shellingham==1.5.4
      - sigtools==4.0.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - sympy==1.14.0
      - synchronicity==0.10.2
      - tabulate==0.9.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - tqdm==4.67.1
      - triton==3.4.0
      - typer==0.17.4
      - types-certifi==2021.10.8.3
      - types-toml==0.10.8.20240310
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.21.1
      - watchfiles==1.1.0
      - websockets==12.0
      - xxhash==3.5.0
      - yarl==1.20.1
prefix: /home/sarvp-srk/miniconda3/envs/metamon
